# This workflow will install Python dependencies, run tests and lint with a single version of Python.
# Creation static html documentation file and add to the PR.
#
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Houston Service - API documentation workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repository: tranquilitybase-io/tb-houston-service
        path: .
    - name: Install redoc-cli and generate API documentation
      run: |
        echo ${GITHUB_HEAD_REF}
        git fetch
        git checkout ${GITHUB_HEAD_REF}
        npm install redoc-cli
        npx redoc-cli bundle openapi/houston_service.yml --title "Houston Service REST API"
        git config user.email action@github.com
        git config user.name "Github Action"
        git commit -m "Add automatically generated redoc HTML documentation" -a
        ls -alrt redoc-static.html
        git commit -m "Add automatically generated redoc HTML documentation" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

